services:
  - type: web
    name: compliment-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:handler
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 